#+title: Shanties
#+HTML_HEAD_EXTRA: <style>p.verse{white-space: pre; font-family: monospace; line-height: 0.6;}</style>
#+OPTIONS: prop:t
#+export_file_name: index.html

#+latex: \clearpage
* 1, 2, 3, 4
:PROPERTIES:
:Artist:   Alan Doyle
:END:
#+begin_verse
Whiskey, whiskey
The singer’s getting sore
We raised the roof
Now we’re lowering the floor
The band is blistered but we’ve got a little bit more
When I say 1,2 you say 3,4
1,2,3,4

Altogether
Altogether gone
It’s now or never if you want another song
On and on goes the ringing of the bell
Off we go, this song won’t sing itself
So soldiers at my side
It’s you and me tonight
Whiskey, whiskey
The singer’s getting sore
We raised the roof
Now we’re lowering the floor
The band is blistered but we’ve got a little bit more
When I say 1,2 you say 3,4
1,2,3,4

Mister moonlight
You gotta let ‘em play
If the devils wanna dance
Then the piper wants his pay
Hide me in a hiding place
Where good sense never goes
Take me to the fountain
Where the firewater flows
Find our alibies and lies
And lose ourselves tonight

Whiskey, whiskey
The singer’s getting sore
We raised the roof
Now we’re lowering the floor
The band is blistered but we’ve got a little bit more
When I say 1,2 you say 3,4
1,2,3,4
Trying to get the whole room on the dance floor
Is like trying to put a square peg in a round hole
I’m not saying it ain’t something that we shouldn’t try to do
Don’t do it for me though, do it for you
You’ve been minding your manners and behaving yourself
But there’s still a lot of bottles left upon the shelf
So wet my little whistle now and give a dog a bone
I can take it up a notch, can’t do it alone
So soldiers at my side
It’s you and me tonight

Whiskey, whiskey
The singer’s getting sore
We raised the roof
Now we’re lowering the floor
The band is blistered but we’ve got a little bit more
When I say 1,2 you say 3,4
1,2,3,4
#+end_verse
#+latex: \clearpage
* A Pirates Life For Me
#+begin_verse
Yo ho, yo ho, a pirate's life for me
We pillage, we plunder, we rifle, and loot
Drink up, me 'earties, yo ho
We kidnap and ravage and don't give a hoot
Drink up me 'earties, yo ho

Yo ho, yo ho, a pirate's life for me
We extort, we pilfer, we filch, and sack
Drink up, me 'earties, yo ho
Maraud and embezzle, and even high-jack
Drink up, me 'earties, yo ho

Yo ho, yo ho, a pirate's life for me
We kindle and char, inflame and ignite
Drink up, me 'earties, yo ho
We burn up the city, we're really a fright
Drink up, me 'earties, yo ho

We're rascals, scoundrels, villans, and knaves
Drink up, me 'earties, yo ho
We're devils and black sheep, really bad eggs
Drink up, me 'earties, yo ho

Yo ho, yo ho, a pirate's life for me
We're beggars and blighters, ne'er-do-well cads
Drink up, me 'earties, yo ho
Aye, but we're loved by our mommies and dads
Drink up, me 'earties, yo ho
#+end_verse
#+latex: \clearpage
* Barrett's Privateers
#+begin_verse
[Verse 1]
Oh, the year was 1778
How I wish I was in Sherbrooke now
A letter of marque came from the king
To the scummiest vessel I've ever seen
God damn them all! I was told
We'd cruise the seas for American gold
We'd fire no guns, shed no tears
But I'm a broken man on a Halifax pier
The last of Barrett's Privateers
[Verse 2]
Oh, Elcid Barrett cried the town
How I wish I was in Sherbrooke now
For twenty brave men all fishermen who
Would make for him the Antelope's crew
God damn them all! I was told
We'd cruise the seas for American gold
We'd fire no guns, shed no tears
But I'm a broken man on a Halifax pier
The last of Barrett's Privateers

[Verse 3]
The Antelope sloop was a sickening sight
How I wish I was in Sherbrooke now
She'd a list to the port and her sails in rags
And the cook in the scuppers with the staggers and jags
God damn them all! I was told
We'd cruise the seas for American gold
We'd fire no guns, shed no tears
But I'm a broken man on a Halifax pier
The last of Barrett's Privateers

[Verse 4]
On the King's birthday we put to sea
How I wish I was in Sherbrooke now
We were 91 days to Montego Bay
Pumping like madmen all the way
God damn them all! I was told
We'd cruise the seas for American gold
We'd fire no guns, shed no tears
But I'm a broken man on a Halifax pier
The last of Barrett's Privateers
[Verse 5]
On the 96th day we sailed again
How I wish I was in Sherbrooke now
When a bloody great Yankee hove in sight
With our cracked four pounders we made to fight
God damn them all! I was told
We'd cruise the seas for American gold
We'd fire no guns, shed no tears
But I'm a broken man on a Halifax pier
The last of Barrett's Privateers

[Verse 6]
Now the Yankee lay low down with gold
How I wish I was in Sherbrooke now
She was broad and fat and loose in the stays
But to catch her took the Antelope two whole days
God damn them all! I was told
We'd cruise the seas for American gold
We'd fire no guns, shed no tears
But I'm a broken man on a Halifax pier
The last of Barrett's Privateers

[Verse 7]
Then at length we stood two cables away
How I wish I was in Sherbrooke now
Our cracked four pounders made an awful din
But with one fat ball, the Yank stove us in
God damn them all! I was told
We'd cruise the seas for American gold
We'd fire no guns, shed no tears
But I'm a broken man on a Halifax pier
The last of Barrett's Privateers
[Verse 8]
The Antelope shook and pitched on her side
How I wish I was in Sherbrooke now
Barrett was smashed like a bowl of eggs
And the Main truck carried off both me legs
God damn them all! I was told
We'd cruise the seas for American gold
We'd fire no guns, shed no tears
But I'm a broken man on a Halifax pier
The last of Barrett's Privateers

[Verse 9]
So here I lay in my 23rd year
How I wish I was in Sherbrooke now
It's been 6 years since we sailed away
And I just made Halifax yesterday
God damn them all! I was told
We'd cruise the seas for American gold
We'd fire no guns, shed no tears
But I'm a broken man on a Halifax pier
The last of Barrett's Privateers
#+end_verse
#+latex: \clearpage
* Beneath the Black Flag
#+begin_verse
Out on the endless ocean
We tear along the gales
With rum inside our bellies warm
And freedom in our sails

A wayward bunch of scoundrels
Assassins, thieves and slaves
The rich and blue-bloods fear us when
We hunt upon the waves

And when you see it coming
That flag of baleful black
No point in turning tail there's no
Escaping our attack!
YO-HO!
YO-HO!
We row beneath the black flag
A rollickin' we go!
We own the sea and sky
YO-HO!
YO-HO!
We row beneath the black flag
A rollickin' we go!
We bleed the kingdoms dry!

Defy the odds against us
A pirate knows no fear
Our steel is ready and our
Retribution is severe

We plunder from the greedy
With blood and with our steel
We rob the rich of their
Ill-gotten gain and make them kneel

Behold the ocean's mysteries
The tales of ancient deeds
We follow in the footsteps
Of a silent secret creed
Come on, lads!

YO-HO!
YO-HO!
We row beneath the black flag
A rollickin' we go!
We own the sea and sky
YO-HO!
YO-HO!
We row beneath the black flag
A rollickin' we go!
We bleed the kingdoms dry!

Hoist the black flag, lads!

Justice runs in crimson rivers...

YO-HO!
YO-HO!
We row beneath the black flag
A rollickin' we go!
We own the sea and sky
YO-HO!
YO-HO!
We row beneath the black flag
A rollickin' we go!
We own the sea and sky
YO-HO!
YO-HO!
We row beneath the black flag
A rollickin' we go!
We bleed the kingdoms dry!
#+end_verse
#+latex: \clearpage
* Binks' Brew
:PROPERTIES:
:Artist:   One Piece
:END:
#+begin_verse
Yo-hohoho, Yo-hoho-ho,
Yo-hohoho, Yo-hoho-ho,
Yo-hohoho, Yo-hoho-ho,
Yo-hohoho, Yo-hoho-ho,
Gather up all of the crew!
It's time to ship out Bink's brew!
Sea wind blows. To where?
Who knows?
The waves will be our guide!
O'er across the ocean's tide,
Rays of sunshine far and wide,
Birds they sing of cheerful things, in circles passing by!
Bid farewell to weaver's town!
Say so long to port renowned!
Sing a song, it won't be long, before we're casting off!
Cross the gold and silver seas
The salty spray puts us at ease!
Day and night to our delight,
The voyage never ends!
Gather up all of the crew!
It's time to ship out Bink's brew!
Pirates we, eternally are challenging the sea!
With the waves to rest our heads,
ship beneath us as our beds!
Hoisted high upon the mast our Jolly Roger flies!
Somewhere in the endless sky,
Stormy winds are blowin' by!
Waves are dancing, evening comes,
It's time to sound the drums!
But steady men may never fear!
Tomorrow's skies are always clear!
So pound your feet and clap your hands till sunny days return!

Yo-hohoho, Yo-hoho-ho,
Yo-hohoho, Yo-hoho-ho,
Yo-hohoho, Yo-hoho-ho,
Yo-hohoho, Yo-hoho-ho,
Gather up all of the crew!
It's time to ship out Bink's brew!
Wave good-bye, but don't you cry
Our memories remain.
Our days are but a passing dream, everlasting though they seem
'neath the moon we'll meet again, the wind's our lullaby!
Gather up all of the crew!
It's time to ship out Bink's brew!
Sing a song and play along
For all the ocean's wide!
After all is said and done,
you'll end up a skeleton!
So spread your tale, from dawn till dusk, upon these foamy seas!
Yo-hohoho, Yo-hoho-ho,
Yo-hohoho, Yo-hoho-ho,
Yo-hohoho, Yo-hoho-ho,
Yo-hohoho, Yo-hoho-ho.
#+end_verse
#+latex: \clearpage
* TODO Brave and Mighty Sailin' Captain
:PROPERTIES:
:Artist:   Musical Blades
:END:

#+latex: \clearpage
* Bully in the Alley
#+begin_verse
[Chorus]
Help me, Bob, I'm bully in the alley
Way-hey, hey-hey, bully in the alley
Help me, Bob, I'm bully in the alley
Bully down in shinbone al!

[Verse 1]
Sally is the girl that I love dearly
Way-hey, hey-hey, bully in the alley
Sally is the girl that I spliced dearly
Bully down in shinbone al!
[Chorus]
Help me, Bob, I'm bully in the alley
Way-hey, hey-hey, bully in the alley
Help me, Bob, I'm bully in the alley
Bully down in shinbone al!

[Verse 2]
For seven long years I courted little Sally
Way-hey, hey-hey, bully in the alley
But all she did was dilly and dally
Bully down in shinbone al!

[Chorus]
Help me, Bob, I'm bully in the alley
Way-hey, hey-hey, bully in the alley
Help me, Bob, I'm bully in the alley
Bully down in shinbone al!

[Verse 3]
I ever get back, I'll marry little Sally
Way-hey, hey-hey, bully in the alley
Have six kids and live in Shin-bone Alley
Bully down in shinbone al!

[Chorus]
Help me, Bob, I'm bully in the alley
Way-hey, hey-hey, bully in the alley
Help me, Bob, I'm bully in the alley
Bully down in shinbone al!
#+end_verse
#+latex: \clearpage
* Captain Kidd
#+begin_verse
My name is Captain Kidd
As I sailed, as I sailed,
Oh my name is Captain Kidd as I sailed,
My name is Captain Kidd
And God's laws I did forbid,
And most wickedly I did as I sailed.

My father taught me well
To shun the gates of hell,
But against him I rebelled as I sailed,
He shoved a bible in my hand
But I left it in the sand
And I pulled away from land,
As I sailed

[Chorus]

I murdered William Moore
And I left him in his gore
Twenty leagues away from shore
As I sailed,
And being crueler still, the gunner I did kill
All his precious blood did spill,
As I sailed,

[Chorus]

I was sick and nigh to death,
And I vowed at every breath,
Oh to walk in wisdom's path,
As I sailed
But my repentance lasted not,
My vows I soon forgot,
Oh damnation is my lot,
As I sailed.

[Chorus]

To the execution dock
Lay my head upon the block,
Laws no more I'll mock as I sail,
So take warning here and heed
To shun bad company
Or you'll wind up just like me
As I sailed.
#+end_verse
#+latex: \clearpage
* Captain Morgan
:PROPERTIES:
:Title:    Captain Morgan
:Artist:   Jolly Rogers
:END:
#+begin_verse
Eight months out, nothing to show
The crew's morale at an all time low
When we pulled in to Port Royal for repairs
The Captain went ashore for news
While we mended sails with the other crews
And talked about our sad state of affairs

The captain, he came bounding back
He said "Boys, there's no time to unpack
'cause we're about to join our pirate fleet"
This news should have been met with cheers
But the crew was plagued with doubt and fears
So the captain said without missing a beat:

"Don't avoid it, don't fear it
Embrace your pirate spirit
We sail with Captain Morgan tonight"

"For adventure and glory
And an unforgettable story
We sail with Captain Morgan tonight!"

"For Maracaibo we'll set sail
And there is no way we can fail
We'll have us a Navy of our own"

Like Portobello long before
We will sneak ourselves ashore
And we'll be rich before we come back home"

This got some cheers but not a lot
They knew the Cartagena plot
And all the pirates there that met their end

"Yes" he says "there's risk involved
But every problem can be solved
And we'll end up with more cash than we can spend"
"Don't avoid it, don't fear it
Embrace your pirate spirit
We sail with Captain Morgan tonight"

"For adventure and glory
And an unforgettable story
We sail with Captain Morgan tonight!"

At last the crew they all agreed
As fear cannot win over greed
And we got our ship all ready and primed

We set the sails and sharpened swords
We pulled the anchor and wound the cords
There was no way that we would lose this time

With that the whole crew was met
Pledges made, and routes were set
Henry Morgan said "Let not a thing go wrong!"

And as the fleet was heading out
You could hear our whole crew shout
"Listen up ye scurvy dogs and sing along;

"Don't avoid it, don't fear it
Embrace your pirate spirit
We sail with Captain Morgan tonight"
"For adventure and glory
And an unforgettable story
We sail with Captain Morgan tonight!"
#+end_verse
#+latex: \clearpage
* Diggy Diggy Hole
:PROPERTIES:
:Artist:   Wind Rose
:END:
#+begin_verse
[Verse 1]
Brothers of the mine rejoice!
(Swing, swing, swing with me!)
Raise your pick and raise your voice!
(Sing, sing, sing with me!)
Down and down into the deep
Who knows what we'll find beneath?
Diamonds, rubies, gold, and more
Hidden in the mountain store

[Pre-Chorus 1]
Born underground
Suckled from a teat of stone
Raised in the dark
The safety of our mountain home
Skin made of iron
Steel in our bones
To dig and dig makes us free
Come on, brothers, sing with me!
[Chorus]
I am a dwarf and I'm digging a hole
Diggy diggy hole, diggy diggy hole
I am a dwarf and I'm digging a hole
Diggy diggy hole, digging a hole

[Verse 2]
The sunlight will not reach this low
(Deep, deep in the mine)
Never seen the blue moon glow
(Dwarves won't fly so high)
Fill a glass and down some mead
Stuff your bellies at the feast!
Stumble home and fall asleep
Dreaming in our mountain keep

[Pre-Chorus 2]
Born underground
Grown inside a rocky womb
The Earth is our cradle
The mountain shall become our tomb
Face us on the battlefield
You will meet your doom
We do not fear what lies beneath
We can never dig too deep
[Chorus]
I am a dwarf and I'm digging a hole
Diggy diggy hole, diggy diggy hole
I am a dwarf and I'm digging a hole
Diggy diggy hole, digging a hole

[Chorus]
I am a dwarf and I'm digging a hole
Diggy diggy hole, diggy diggy hole
I am a dwarf and I'm digging a hole
Diggy diggy hole, digging a hole

[Instrumental]

[Pre-Chorus 1]
Born underground
Suckled from a teat of stone
Raised in the dark
The safety of our mountain home
Skin made of iron
Steel in our bones
To dig and dig makes us free
Come on, brothers, sing with me!

[Chorus]
I am a dwarf and I'm digging a hole
Diggy diggy hole, diggy diggy hole
I am a dwarf and I'm digging a hole
Diggy diggy hole, digging a hole
[Chorus]
I am a dwarf and I'm digging a hole
Diggy diggy hole, diggy diggy hole
I am a dwarf and I'm digging a hole
Diggy diggy hole, digging a hole
#+end_verse
#+latex: \clearpage
* Don't Forget Your Old Shipmate
#+begin_verse
Safe and sound at home again, let the waters roar, Jack
Safe and sound at home again, let the waters roar, Jack

Long we've tossed on the rolling main
Now we're safe ashore, Jack
Don't forget yer old shipmate
Faldee raldee raldee raldee rye-eye-doe!

Since we sailed from Plymouth Sound, four years gone, or nigh, Jack
Was there ever chummies, now, such as you and I, Jack?
Long we've tossed on the rolling main
Now we're safe ashore, Jack
Don't forget yer old shipmate
Faldee raldee raldee raldee rye-eye-doe!

We have worked the self-same gun, quarterdeck division
Sponger I and loader you, through the whole commission

Long we've tossed on the rolling main
Now we're safe ashore, Jack
Don't forget yer old shipmate
Faldee raldee raldee raldee rye-eye-doe!

Oftentimes have we laid out, toil nor danger fearing
Tugging out the flapping sail to the weather earring

Long we've tossed on the rolling main
Now we're safe ashore, Jack
Don't forget yer old shipmate
Faldee raldee raldee raldee rye-eye-doe!

When the middle watch was on, and the time went slow, boy
Who could choose a rousing stave, who like Jack or Joe, boy?

Long we've tossed on the rolling main
Now we're safe ashore, Jack
Don't forget yer old shipmate
Faldee raldee raldee raldee rye-eye-doe!
There she swings, an empty hulk, not a soul below now
Number seven starboard mess misses Jack and Joe now

Long we've tossed on the rolling main
Now we're safe ashore, Jack
Don't forget yer old shipmate
Faldee raldee raldee raldee rye-eye-doe!

But the best of friends must part, fair or foul the weather
Hand yer flipper for a shake, now a drink together

Long we've tossed on the rolling main
Now we're safe ashore, Jack
Don't forget yer old shipmate
Faldee raldee raldee raldee rye-eye-doe!

Long we've tossed on the rolling main
Now we're safe ashore, Jack
Don't forget yer old shipmate
Faldee raldee raldee raldee rye-eye-doe!
#+end_verse
#+latex: \clearpage
* Drunken Sailor
#+begin_verse

What do you do with a drunken sailor
What do you do with a drunken sailor
What do you do with a drunken sailor
Earl-eye in the morning

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Earl-eye in the morning

Shave his belly with a rusty razor
Shave his belly with a rusty razor
Shave his belly with a rusty razor
Earl-eye in the morning

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Earl-eye in the morning

Put him in the hold with the Captain's daughter
Put him in the hold with the Captain's daughter
Put him in the hold with the Captain's daughter
Earl-eye in the morning

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Earl-eye in the morning

What do you do with a drunken sailor
What do you do with a drunken sailor
What do you do with a drunken sailor
Earl-eye in the morning

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Earl-eye in the morning

Put him in the back of the paddy wagon
Put him in the back of the paddy wagon
Put him in the back of the paddy wagon
Earl-eye in the morning

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Earl-eye in the morning

Throw him in the lock-up 'til he's sober
Throw him in the lock-up 'til he's sober
Throw him in the lock-up 'til he's sober
Earl-eye in the morning

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Earl-eye in the morning

What do you do with a drunken sailor
What do you do with a drunken sailor
What do you do with a drunken sailor
Earl-eye in the morning

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Earl-eye in the morning

What do you do with a drunken sailor
What do you do with a drunken sailor
What do you do with a drunken sailor
Earl-eye in the morning

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Earl-eye in the morning

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Earl-eye in the morning!
#+end_verse
#+latex: \clearpage
* Eight Bells
:PROPERTIES:
:Artist:   Jolly Rogers
:END:
#+begin_verse
"This will be our home me boys
So I trust you'll treat her right."
'Twas how the captain speech began
Each voyage's first night
He smiled said "It's tradition
But I asked that you refrain
From carving your name in the beam
Next to her lofty mane."

The first night I was there
Her mates held me in the air
And let me carve my name with theirs
To show that I was there
From boy to man we grew up as
Across the waves we roamed
As she heard me sob likе sons who'd lost their childhood home
Eight bells rang out in Dovеr
Eight bells rang out in Wales
Eight bells rang out in Liverpool
And Down to Murphy's scales
Eight bells rang out in Port Royale
Eight bells rang out in Boston town
Eight bells rang out in Nassau
The night the Merry Widow went down

As a mere midshipman's mate
I'd stare up at that beam
And knew that every name I saw
Was shared between a dream
Some of them so faded just a memory and a scratch
But they grew much clearer with every new batch
She made sure we made it back
To the lands we longed
And with the tide we all returned to the vessel we call home
There were parts we could have salvaged but I think we all agreed
That she deserved the honor of a burial at sea

Eight bells rang out in Dover
Eight bells rang out in Wales
Eight Bells rang out in Liverpool
And down to murphy's scales
Eight bells rang out in Port Royale
Eight bells rang out in Boston town
Eight bells rang out in Nassau
The night the Merry Widow went down
By the time I was the bos'n, the list was 3 yards long
Though she had seen so many years, she still stood tall and strong
But the name she took her spirit
Bold and strong and true
And she raced the wind and never failed her brave and loyal crew

The ship she never floundered
Her defenses never breached
No matter her port of call her goal was always reached
When we were told her day had come and she had sailed her last
That they were tear her down for scrap
We couldn't let that pass

Eight bells rang out in Dover
Eight bells rang out in Wales
Eight Bells rang out in Liverpool
And down to murphy's scales
Eight bells rang out in Port Royale
Eight bells rang out in Boston town
Eight bells rang out in Nassau
The night the Merry Widow went down

Through our grief we'd swore an oath
That we'd carry out our plan
And damn the risk we would push on to the strength of our last man
And as we stared at all the names of those that came before
We cut the line and stole that ship and sailed her out once more
Beyond the reef we sailed her
And set our love alight
We jumped ship and watched her burn from the shore that night
As she sank beneath the waves, we knew one thing for sure
She made more of a mark on us
Than we ever did on her
Eight bells rang out in Dover
Eight bells rang out in Wales
Eight Bells rang out in Liverpool
And down to murphy's scales
Eight bells rang out in Port Royale
Eight bells rang out in Boston town
Eight bells rang out in Nassau
The night the Merry Widow went down

Eight bells rang out…
Eight bells rang out…
The night the Merry Widow went down
The night the Merry Widow went down
#+end_verse
#+latex: \clearpage
* Farewell and Adieu / Spanish Ladies
#+begin_verse
Farewell and adieu to you fair Spanish ladies
Farewell and adieu to you ladies of Spain
Cause we’ve received orders to sail for old England
But we hope in a short time to see you again

We’ll rant and we’ll roar like true British sailors
We’ll rant and we’ll rave across the salt seas
Until we strike soundings in the Channel of England
From Ushant to Scilly is thirty-four leagues

We hove our ship to, with the wind at southwest, boys
We hove our ship to, for to take soundings clear
In fifty-five fathoms with a fine sandy bottom
We filled our main tops’l, up Channel did steer
We’ll rant and we’ll roar like true British sailors
We’ll rant and we’ll rave across the salt seas
Until we strike soundings in the Channel of England
From Ushant to Scilly is thirty-four leagues

The first land we made was a point called the Deadman
Next Ram's Head off Plymouth, Start, Portland, and Wight
We sailed then by Beachy, by Fairlee and Dover
Then bore straight away for the South Foreland Light

We’ll rant and we’ll roar like true British sailors
We’ll rant and we’ll rave across the salt seas
Until we strike soundings in the Channel of England
From Ushant to Scilly is thirty-four leagues

Now the signal was made for the Grand Fleet to anchor
We glued up our tops’ls, stuck out tacks and sheets
We stood by our stoppers, we brailed in our spankers
Then anchored ahead of the noblest of fleets

We’ll rant and we’ll roar like true British sailors
We’ll rant and we’ll rave across the salt seas
Until we strike soundings in the Channel of England
From Ushant to Scilly is thirty-four leagues

Let every man here drink up his full bumper
Let every man here drink up his full bowl
And let us be jolly and drown melancholy
Singing, here’s a good health to each true-hearted lass
We’ll rant and we’ll roar like true British sailors
We’ll rant and we’ll rave across the salt seas
Until we strike soundings in the Channel of England
From Ushant to Scilly is thirty-four leagues
#+end_verse
#+latex: \clearpage
* Finnegan's Wake
#+begin_verse
Tim Finnegan lived in Walken' Street
A gentleman Irishman mighty odd;
He seen a brogue so soft and sweet
And to rise in the world he carried the hod

Tim had a sort of a tipplin' way
With a love of the liquor now he was born
To help him on with his work each day
Had a "drop of the cray-chur" every morn

Whack fol the da O, dance to your partner
Welt the floor, your trotters shake;
Wasn't it the truth I told you?
Lots of fun at Finnegan's wake!
One mornin' Tim felt rather full
His head felt heavy which made him shake;
Fell from a ladder and he burst his skull
So they carried him home his corpse to wake

Rolled him up in a nice clean sheet
Laid him out upon the bed;
A gallon of whiskey at his feet
A barrel of porter at his head

Whack fol the da O, dance to your partner
Welt the floor, your trotters shake;
Wasn't it the truth I told you?
Lots of fun at Finnegan's wake!

His friends assembled at the wake
And Mrs. Finnegan called for lunch
First they brung in tea and cake;
Then pipes, tobacco and whiskey punch

Biddy O'Brien began to cry
"Such a nice clean corpse, did you ever see?
Tim mavournin, why did you die?"
Arragh, shut your gob said Paddy McGhee!

Whack fol the da O, dance to your partner
Welt the floor, your trotters shake;
Wasn't it the truth I told you?
Lots of fun at Finnegan's wake!
Patty O'Connor took up the job
"Ah Biddy," says she, "You're wrong, I'm sure"
Biddy gave her a belt in the gob
Then left her sprawlin' on the floor

Then the war did soon enrage
Woman to woman and man to man
Shillelagh-law was all the rage
And a row and a ruction soon began

Mickey Maloney lowered his head
And a bottle of whiskey flew at him
Missed, and fallin' on the bed
The liquor scattered over Tim!

Tim revives! See how he rises!
Timothy risin' from the bed
Sayin', "Whirl your liquor around like blazes
Thunderin' Jaysus! Do you thunk I'm dead?"

Whack fol the da O, dance to your partner
Welt the floor, your trotters shake;
Wasn't it the truth I told you?
Lots of fun at Finnegan's wake!
#+end_verse
#+latex: \clearpage
* Flyin' Dutchman
:PROPERTIES:
:Title: Flyin' Dutchman
:Artist: Jolly Rogers
:END:
** Lyrics
#+begin_verse
The sky was grey and cloudy
And the wind was from the west
When we spied a battered frigate
With her tattered sail full dressed
They signaled they had letters home
They asked if we could take
They dropped them in a barrel
They left bobbing in their wake
We reefed the sails and slowed the ship
To fish they barrel out
The old ship sailed to the distance
And we saw her come about
The captain watched through a spy-glass
And we heard him catch his breath
And we saw the storm a-brewing
Had become a wall of death

Turn this ship around me boys
Turn around and run!
That storm it wants a battle
And it's sure that were outgunned!
What of the ship that's out there
Do we leave her to the gale?
She's called the Flying Dutchman
And it's rage that fills her sails!

The thunder growled like demons
And the lightning stabbed the waves
And the Dutchman she leapt t'wards us
Riding fury from the graves
Our captain, he stayed at the wheel
The crew they manned the lines
And still that ship and storm
Were quickly closing in behind
Our ship we crest a giant wave
And crashed to the trough below
And the crew held on to what they could
They were damned if they let go
The rain and sea and storm winds
Crashed against our ship with wrath
And from the deck of that cursed ship
We could hear them laugh

Turn this ship around me boys!
Turn around and run!
That storm it wants a battle
And it's sure that we're outgunned!
That ghostly ship is hunting us
It's bringing on the gale!
She's called the Flying Dutchman
And it's rage that fills her sails!

That was when we sighted land
It became a race with time
We believed it Santa Marta
The Dutchman closing in behind
"Risk it all!" the captain cried
"It's the only chance we got!"
Salvation if we make it
And our souls if we get caught
The storm was all around us
And the Dutchman cut our wind
The beast nearly capsized up
And we watched our strong mast bend
We were almost to the harbor
We could see the natural break
And each man willed her forward
For they knew what was at stake

Once we charged into that harbor
The Dutchman heaved away
And we heard their bitter screams
For the devil lost his prey
Once we made it safely
To the leeward of the bay
We cracked that barrel open
To see what those letters say
There must have been a hundred
And that's when we realized
These moldy parchments were addressed
To those who'd long since died
If you see a battered frigate
‘neath a grey and stormy sky
Give way and watch behind you
Or you'll hear your captain cry
#+end_verse
** Chords
#+begin_verse
[Intro]
Dm Dm

[Verse]
Dm
The sky was grey and cloudy and the wind was from the west

When we spied a battered frigate with her tattered sail full dressed

Gm
They signaled they had letters home they asked if we could take

Dm
They dropped 'em in a barrel they left bobbing in their wake


Dm
We reefed the sails and slowed the ship to fish the barrel out

The old ship sailed to the distance and we saw her come about

Gm
The captain watched through a spyglass and we heard him catch his breath

Dm
And we saw the storm a-brewing had become a wall of death

[Chorus]
A                              G
Turn this ship around me boys, turn around and run

A                                     G
This storm it wants a battle and it's sure that we're outgunned

Dm                       F               G                A
What of the ship that's out there do we leave her to the gale?

N.C.
She's called the Flying Dutchman and it's wraiths that fills her sails.

Dm Dm Dm Dm

[Verse]
Dm
The thunder growled like demons and the lightening stabbed the waves

And the Dutchman she lept towards us riding fury from the graves

Gm
Our captain he stayed at the wheel, the crew the manned the lines,

Dm
And still that ship and storm were quickly closing in behind.



Dm
Our ship we crest a giant wave and crash to the trough below

The crew held on to what they could, they were damned if they let go.

Gm
The rain and sea and storm winds crashed against our ship with wrath

Dm
And from the deck of that cursed ship, we could hear them laugh

[Chorus]
A                              G
Turn this ship around me boys, turn around and run

A                                     G
This storm it wants a battle and it's sure that we're outgunned

Dm                    F                G               A
That ghostly ship is hunting us, it's bringing on the gale,

N.C.
She's called the Flying Dutchman and it's wraiths that fills her sails

[Verse]
Dm
That was when we sighted land, it became a race wih time

We believed it Santa Marta, the Dutchman closing in behind

Gm
"Risk it all" the captain cried "it's the only chance we've got,

Dm
Salvation if we make it and our souls if we get caught."

Dm
The storm was all around us and the Dutchman cut our winds,

The beast nearly capsized us, and we watched our strong mast bend

Gm
We were almost to the harbour, we could see the natural break,

Dm
And each man willed her forward, for they knew what was at stake

[Chorus]
A                              G
Turn this ship around me boys, turn around and run

A                                     G
This storm it wants a battle and it's sure that we're outgunned

Dm                    F                G               A
That ghostly ship is hunting us, it's bringing on the gale,

N.C.
She's called the Flying Dutchman and it's wraiths that fills her sails

[Verse]
Dm
Once we charged into that harbour, the Dutchman heaved away

And we heard their bitter screams, for the Devil lost his prey.

Gm
Once we made it safely to the leeward of the bay,

Dm
We cracked that barrel open to see what those letters say.


Dm
There must've been a hundred and that's when we realized,

Those moldy parchments were addressed to those who'd long since died.

Gm
If you see a battered frigate 'neath a grey and stormy sky,

Dm
Give way and watch mehind you, or you'll hear your captain cry:


[Chorus]
A                              G
Turn this ship around me boys, turn around and run

A                                     G
This storm it wants a battle and it's sure that we're outgunned

Dm                    F                G               A
That ghostly ship is hunting us, it's bringing on the gale,

N.C.
She's called the Flying Dutchman and it's wraiths that fills her sails
#+end_verse
#+latex: \clearpage
* Fucked with an Anchor
:PROPERTIES:
:Artist:   Jolly Rogers
:END:
#+begin_verse
Fuck you, you're a fucking wanker
We're gonna punch you right in the balls
Fuck you with a fucking anchor
You're all cunts so fuck you all
Fuck you, you're a fucking wanker
We're gonna punch you right in the balls
Fuck you with a fucking anchor
You're all cunts so fuck you all

(Go!)

For thirty odd years, I have lived with this curse
My vocabulary was stunted at birth
By a witch doctor from over the seas
Casting a strange voodoo magic on me
Now when I speak, it's rather absurd
An endless tirade of four letter words
I lash out in anger at all in my way
Shocking unspeakable things that I say

Fuck you, you're a fucking wanker
We're gonna punch you right in the balls
Fuck you with a fucking anchor
You're all cunts so fuck you all
Fuck you, you're a fucking wanker
We're gonna punch you right in the balls
Fuck you with a fucking anchor
You're all cunts so fuck you all

(Fuck you!)

Long I have waited to have my revenge
To bring that witch doctor to his bitter end
So I have gathered a ship and a crew
We're sailing to find him, we know what to do
On a dark moonless night, when he least suspects
We'll creep up behind him, so hard to detect
We'll bring out our anchor by the light of the stars
And shove it inside of his big fuckin' arse

Fuck you, you're a fucking wanker
We're gonna punch you right in the balls
Fuck you with a fucking anchor
You're all cunts so fuck you all
Fuck you, you're a fucking wanker
We're gonna punch you right in the balls
Fuck you with a fucking anchor
You're all cunts so fuck you all

Fuck you, you're a fucking wanker
We're gonna punch you right in the balls
Fuck you with a fucking anchor
You're all cunts so fuck you all
Fuck you, you're a fucking wanker
We're gonna punch you right in the balls
Fuck you with a fucking anchor
You're all cunts so fuck you all

(Wank!)
#+end_verse
#+latex: \clearpage
* Haul Away Joe
#+begin_verse
[Verse 1]
When I was just a little lad, or so me Mammi told me
Away Haul Away, we'll haul away, Joe
That if I didn't kiss the girls me lips would grow all mouldy
Away Haul Away, we'll haul away, Joe

[Chorus]
Away! HO! Haul away, we'll haul away together
Away Haul Away, we'll haul away, Joe
Away! HO! Haul away, we'll hope for better weather
Away Haul Away, we'll haul away, Joe
[Verse 2]
I used to have an Irish girl but she got fat and lazy
Away Haul Away, we'll haul away, Joe
But now I've got a Bristol girl and she just drives me crazy
Away Haul Away, we'll haul away, Joe

[Chorus]
Away! HO! Haul away, we'll haul away together
Away Haul Away, we'll haul away, Joe
Away! HO! Haul away, we'll hope for better weather
Away Haul Away, we'll haul away, Joe

[Verse 3]
Oh Louis was the king of France before the Revolut-i-on
Away Haul Away, we'll haul away, Joe
Then he got his head chopped off & it spoiled his constitut-i-on
Away Haul Away, we'll haul away, Joe

[Chorus]
Away! HO! Haul away, we'll haul away together
Away Haul Away, we'll haul away, Joe
Away! HO! Haul away, we'll hope for better weather
Away Haul Away, we'll haul away, Joe

[Verse 4]
Ya call yourself a "Second Mate", ya cann'e tie a bowline
Away Haul Away, we'll haul away, Joe
You can't even stand up straight when the packet, she's a-rollin'
Away Haul Away, we'll haul away, Joe
[Chorus]
Away! HO! Haul away, we'll haul away together
Away Haul Away, we'll haul away, Joe
Away! HO! Haul away, we'll hope for better weather
Away Haul Away, we'll haul away, Joe

[Verse 5]
Well now can't ya see... the black clouds a-gatherin'
Away Haul Away, we'll haul away, Joe
Well now can't ya see... the storm clouds a-risin'
Away Haul Away, we'll haul away, Joe

[Chorus]
Away! HO! Haul away, we'll haul away together
Away Haul Away, we'll haul away, Joe
Away! HO! Haul away, we'll hope for better weather
Away Haul Away, we'll haul away, Joe
#+end_verse
#+latex: \clearpage
* Health to the Company
#+begin_verse
[Verse 1]
Kind friends and companions, come join me in rhyme
Come lift up your voices in chorus with mine;
Come lift up your voices all grief to refrain
For we may or might never all meet here again

[Chorus]
Here's a health to the company and one to my lass
Let us drink and be merry all out of one glass;
Let us drink and be merry all grief to refrain
For we may or might never all meet here again
[Verse 2]
Here's a health to the dear lass that I love so well
For her style and her beauty, sure none can excel
There's a smile on her countenance as she sits on my knee
There's no man in this wide world as happy as me

[Chorus]
Here's a health to the company and one to my lass
Let us drink and be merry all out of one glass;
Let us drink and be merry all grief to refrain
For we may or might never all meet here again

[Verse 3]
Our ship lies at anchor, she's ready to dock
I wish her safe landing, without any shock
If ever I should meet you by land or by sea
(I will always remember your kindness to me.)

[Chorus]
Here's a health to the company and one to my lass
Let us drink and be merry all out of one glass;
Let us drink and be merry all grief to refrain
For we may or might never all meet here again

Here's a health to the company and one to my lass
Let us drink and be merry all out of one glass;
Let us drink and be merry all grief to refrain
For we may or might never all meet here again
#+end_verse
#+latex: \clearpage
* Hoist the Colors
#+begin_verse
The king and his men
Stole the queen from her bed
And bound her in her bones
The seas be ours
And by the powers
Where we will, we'll roam

Yo, ho, all together
Hoist the colours high
Heave ho, thieves and beggars
Never shall we die
Yo, ho, haul together
Hoist the colours high
Heave ho, thieves and beggars
Never shall we die

Some men have died
And some are alive
And others sail on the sea
– With the keys to the cage...
And the Devil to pay
We lay to Fiddler's Green!

The bell has been raised
From it's watery grave...
Do you hear it's sepulchral tone?
We are a call to all
Pay head the squall
And turn your sail toward home!

Yo, ho, all together
Hoist the colours high
Heave ho, thieves and beggars
Never shall we die!
#+end_verse
#+latex: \clearpage
* Hoist Up the Thing
:PROPERTIES:
:Artist:   The Longest Johns
:END:
#+begin_verse
Fresh out of college, with grades straight from Hell
I browsed for a trade at which I could excel
An ad for a ship in need of some manning
Men, sails, and purpose, but lacking a captain

What luck, says I, to find such good fortune!
A few white lies later, I ran down the pier
Bought me a coat and a cutlass or two
Jumped on the deck, and I yelled at the crew:

Hoist up the thing! Batten down the whatsit!
What's that thing spinning? Somebody should stop it!
Turn hard to port! (That's not port) Now I've got it!
Trust me, I'm in control!

I can't sing the shanties, it has to be said
And all of that grog just goes right to my head
Whale meat is gross and I miss a girl's laugh
Five weeks at sea, even Dave seems a catch!

Hoist up the thing! Batten down the whatsit!
What's that thing spinning? Somebody should stop it!
Turn hard to port! (That's not port) Now I've got it!
Trust me, I'm in control!

We've hit icy waters, no land to be seen
The food's getting low and the beer has gone green
There's murmurs of discontent under the deck
If I don't act fast, it could be my neck!

So pull up the charts and those weird gold machines
I see what it says but no clue what it means!
Just pull on some levers and yank on some chains
Feign a bad back till we've landed again

Hoist up the thing! Batten down the whatsit!
What's that thing spinning? Somebody should stop it!
Turn hard to port! (That's not port) Now I've got it!
Trust me, I'm in control!

Hoist up the thing! Batten down the whatsit!
What's that thing spinning? Somebody should stop it!
Turn hard to port! (That's not port) Now I've got it!
Trust me, I'm in control!

Hoist up the thing! Batten down the whatsit!
What's that thing spinning? Somebody should stop it!
Turn hard to port! (That's not port) Now I've got it!
Trust me, I'm in control!

Hoist up the thing! Batten down the whatsit!
What's that thing spinning? Somebody should stop it! (BLOODY HELL!)
Turn hard to port! (This is SHERRY!) Now I've got it! (Screaming)
Trust me, I'm in control! (MUMMY!)
Trust me, I'm in control!
#+end_verse
#+latex: \clearpage
* I'll Have A Beer
:PROPERTIES:
:Artist:   Jolly Rogers
:Title:    I'll Have A Beer
:END:
#+begin_verse
As a boy I led a sheltered life
The son of a farmer and his wife
I met a friend one day in town
Who offered to buy me a round
So we found a pub they call the Drum and Pipe

Barkeep, he asked what will it be
So I said I think I'll have a tea
My friend said that will never do
Told me that I should have a brew
You wouldn't believe the effect it's had on me

Now at every tavern, bar, and pub I go into
I know just exactly what I should do
I say in a voice that all can hear
Sir I think that I will have a beer
Yes, sir I think that I will have a beer

Since then I have traveled far and wide
I have been all over the countryside
One day, while out, on a walk
I met a Scot who liked to talk
And he told me of a drink I've never tried

Now at every tavern, bar, and pub I go into
I know just exactly what I should do
I say in a voice that all can hear
Sir I think I'll have a scotch and beer
Yes, sir I think I'll have a scotch and beer

Spent a Summer on a schooner out at sea
And one old sailor took a shine to me
He warned me of the awful food
But shared a drink he said was good
I'm gonna have to say that I agree

Now at every tavern, bar, and pub I go into
I know just exactly what I should do
I say in a voice that all can hear
Sir I think I'll have rum, scotch, and beer
Yes, sir I think I'll have rum, scotch, and beer

So when I made it back home again
I met up with a dear, old friend
He took me with him too his pub
Which seemed to be a fancy pub
And taught me about the drink of gentlemen

Now at every tavern, bar, and pub I go into
I know just exactly what I should do
I say in a voice that all can hear
Sir I'll have gin, rum, scotch, and beer
Yes, sir I'll have gin, rum, scotch, and beer

I then met a nice, Irish lad
Who said that he thought it was sad
While I've tried all the rest
He said that I had missed the best
And he offered me the last of what he had

Now at every tavern, bar, and pub I go into
I know just exactly what I should do
I say in a voice that all can hear
I'll have whiskey, gin, rum, scotch, and beer
Yes, I'll have whiskey, gin, rum, scotch, and beer
I''ll have whiskey, gin, rum, scotch and beer
I'll have whiskey, gin, rum, scotch and beer

Whiskey
Gin, rum
Scotch and
A beer
#+end_verse
#+latex: \clearpage
* King of the Pirates (DaddyPhatSnaps)
#+begin_verse
Chorus (GameboyJones):
I don't know why you all think that you should doubt me
I’m a pirate and i say that very proudly
When i pull up with my team we stay rowdy
Count it up we're just racking up our bounty
King of the pirates, that'll be me
I will be captain of the seas
King of the pirates, that’ll be me
I will be captain of the seas

Verse 1 (GameboyJones):
When i gum gum stretch with my gum gum neck
I'm just looking at the seas for these dumb scum pest
When i gum gum flex then you know what's next
Like a washed up ship you about to get wrecked
With a gum gum punch when i pull up to your boat
I don't need to brag i don't even to boast
But the Straw Hat crew is the greatest team of G.O.A.T.'s
So when you face us you ain't leaving here afloat
Look at us, run seas
All about the money give us One Piece
Any thought that your crew was just all that
Then you learned a lesson stepping up to the Straw Hat
Got more flow than the navy
Making them sick now i'm feeling real wavy
Others are wasting their time
I’ll get the riches that’s on the grand line
Never back down
All of these villains that bug me are clowns
They underestimate but when i go to gear forth
Not a single one lasting a round
Don't come around, ain’t no one stopping our quest
Not even when there's a hole in my chest
I've got a mission and won't be denied
You will not get the bounty that’s dead or alive
Chorus (GameboyJones):
I don't know why you all think that you should doubt me
I'm a pirate and i say that very proudly
When i pull up with my team we stay rowdy
Count it up we're just racking up our bounty
King of the pirates, that'll be me
I will be captain of the seas
King of the pirates, that'll be me
I will be captain of the seas

Verse 2 (Rustage):
Uh, feeling all the pressure in my ligaments, i'm willing to pummel up anybody who's hurting someone in my crew
Remind you
I'm a jet engine when i'm behind you
My muscles have been fine tuned breaking bones in your spine too
I'll find you like Foxy when you rap going too slow
Pop a pistol in your back like you're Blueno
Big mom on attack full of glucose
Too slow, bury Katakuri that's a tombstone
Oh, got a bounty in the billions
Oh, but it should be in the trillions
Oh, to me y'all look like civilians
Oh, Yonkos, Marines, i be killing em
Training with the dark king
Capable of more than talking
I'm saving Nami or Robin
Or my brother from his past hell
Enel, i'm simply shocking
My Haki will leave em dropping
This pirate will not be stopping
Til i reach the end at Raftel
Pumping the gear and i'm reaching the fourth
Chaos appears when i knock down your doors
Fill em with tears then i'm coming to war
Blood will be smeared when your decked on the floor
Bet you want more? Punches be faster than Kizuru, rage in my eyes when i'm on beat
Strength to my core, fighting until i get rid of you, limits the sky and the One Piece
Chorus (GameboyJones):
I don't know why you all think that you should doubt me
I'm a pirate and i say that very proudly
When i pull up with my team we stay rowdy
Count it up we're just racking up our bounty
King of the pirates, that'll be me
I will be captain of the seas
King of the pirates, that'll be me
I will be captain of the seas
#+end_verse
#+latex: \clearpage
* Leave Her Johnny
#+begin_verse
[Verse 1]
I thought I heard the Old Man say:
"Leave her, Johnny, leave her."
Tomorrow you will get your pay
And it's time for us to leave her

[Chorus]
Leave her, Johnny, leave her!
Oh, leave her, Johnny, leave her!
For the voyage is long and the winds don't blow
And it's time for us to leave her
[Verse 2]
Oh, the wind was foul and the sea ran high
"Leave her, Johnny, leave her!"
She shipped it green and none went by
And it's time for us to leave her

[Chorus]
Leave her, Johnny, leave her!
Oh, leave her, Johnny, leave her!
For the voyage is long and the winds don't blow
And it's time for us to leave her

[Verse 3]
I hate to sail on this rotten tub
"Leave her, Johnny, leave her!"
No grog allowed and rotten grub
And it's time for us to leave her

[Chorus]
Leave her, Johnny, leave her!
Oh, leave her, Johnny, leave her!
For the voyage is long and the winds don't blow
And it's time for us to leave her

[Verse 4]
We swear by rote for want of more
"Leave her, Johnny, leave her!"
But now we're through so we'll go on shore
And it's time for us to leave her

[Chorus]
Leave her, Johnny, leave her!
Oh, leave her, Johnny, leave her!
For the voyage is long and the winds don't blow
And it's time for us to leave her
#+end_verse
#+latex: \clearpage
* Legend of Davy Jones
#+begin_verse
Some say he steers a spectral ship
That's ghostly, grey, and grand
He's doomed to sail the seven seas
And ne'er set foot on land

And if you chance to see him
You'll soon be dead from fright
So sailors tell their children
On a dark and stormy night

Oh Forty fathoms deep he walks
With rusty keys his locker locks
Just like he's half asleep he stalks
Forty fathoms deep
Forty fathoms deep he owns
Each sleeping sailor's soggy bones
The legend they call Davy Jones
At forty fathoms deep

Nor east we sail to Brimstone head
The captain, crew, and I
At sixteen knots we fairly flew
Beneath a darkening sky

Atop the main mast I rode
Near ten stories high
Went up there blew an icy squall
And overboard went I

Oh Forty fathoms deep he walks
With rusty keys his locker locks
Just like he's half asleep he stalks
Forty fathoms deep

Forty fathoms deep he owns
Each sleeping sailor's soggy bones
The legend they call Davy Jones
At forty fathoms deep

I hold my breath I say a prayer
For all those mates who died
I turn my back on Davy Jones
And cast my fears aside
Raise up my head and kick my feet
And toward the light I go
The heartless jailer left behind
The locker far below

Oh Forty fathoms deep he walks
With rusty keys his locker locks
Just like he's half asleep he stalks
Forty fathoms deep

Forty fathoms deep he owns
Each sleeping sailor's soggy bones
The legend they call Davy Jones
At forty fathoms deep
#+end_verse
#+latex: \clearpage
* My Jolly Sailor Bold
#+begin_verse
Upon one summer's morning
I carefully did stray
Down by the Walls of Wapping
Where I met a sailor gay

Conversing with a young lass
Who seem'd to be in pain
Saying, William, when you go
I fear you'll ne'er return again

My heart is pierced by Cupid
I disdain all glittering gold
There is nothing can console me
But my jolly sailor bold

His hair it hangs in ringlets
His eyes as black as coal
My happiness attend him
Wherever he may go

From Tower Hill to Blackwall
I'll wander, weep and moan
All for my jolly sailor
Until he sails home

My heart is pierced by Cupid
I disdain all glittering gold
There is nothing can console me
But my jolly sailor bold

My father is a merchant
The truth I now will tell
And in great London City
In opulence doth dwell

His fortune doth exceed
300,000 gold
And he frowns upon his daughter
Who loves a sailor bold

A fig for his riches
His merchandise and gold
True love has grafted my heart
Give me my sailor bold

My heart is pierced by Cupid
I disdain all glittering gold
There is nothing can console me
But my jolly sailor bold

Should he return in pov'rty
From o'er the ocean far
To my tender bosom
I'll press my jolly tar

My sailor is as smiling
As the pleasant month of May
And often we have wandered
Through Ratcliffe Highway

Many a pretty blooming
Young girl we did behold
Reclining on the bosom
Of her jolly sailor bold

My heart is pierced by Cupid
I disdain all glittering gold
There is nothing can console me
But my jolly sailor bold

My name it is Maria
A merchant's daughter fair
And I have left my parents
And three thousand pounds a year

Come all you pretty fair maids
Whoever you may be
Who love a jolly sailor
That plows the raging sea

While up aloft in storm
From me his absence mourn
And firmly pray arrive the day
He's never more to roam

My heart is pierced by Cupid
I disdain all glittering gold
There is nothing can console me
But my jolly sailor bold
#+end_verse
#+latex: \clearpage
* Nord Mead
#+begin_verse
We're merry men of Skyrim
So sturdy and so stout
When the day is done
When it's time for fun
We'll drink and sing and shout

You weak livered milk drinkers
Can let your throats run dry
Cause there's just one drink
That we will sink
Until the day we die
Drinking mead in the halls of Whiterun
The maidens and the men
We swig our brew
Until we spew
Then we fill our mugs again

You can keep your filthy Skooma
It makes our bellies bleed
Cause when we raise our flagon
To another dead dragon
There is just one drink we need
Nord mead!
Nord mead!

Chug a mug of mead
And another mug of mead
Chug another mug of mead
Till you fall down
Chug a mug of mead
And another mug of mead
Chug another mug of mead, warrior

After the long hard days
Of hunting and of war
Our throats are tired and thirsty
And our bodies drenched in gore
But we won't waste our evenings
Feeling tired and feeling spent
We perk right up when we breathe in
That wholesome honey scent

That Cyrodilic Brandy
Too fruity for these tongues
You can keep your fancy alto wine
It tastes like horker dung!

Balmora Blue tastes great to you
But here we like it plain
Just fill my mug
With the mighty jug
Of honey, heart and grain

Drinking mead in the halls of Whiterun
The maidens and the men
We swig our brew
Until we spew
Then we fill our mugs again

You can keep your filthy Skooma
It makes our bellies bleed
Cause when we raise our flagon
To another dead dragon
There is just one drink we need
Nord mead!
Nord mead!
Nord mead!
Chug a mug of mead
And another mug of mead
Chug another mug of mead
Till you fall down (Nord mead!)
Chug a mug of mead
And another mug of mead
Chug another mug of mead, warrior!
#+end_verse
#+latex: \clearpage
* Oh, Better Far to Live and Die - Pirate King
#+begin_verse
King.
Oh, better far to live and die
Under the brave black flag I fly,
Than play a sanctimonious part,
With a pirate head and a pirate heart.
Away to the cheating world go you,
Where pirates all are well-to-do;
But I?ll be true to the song I sing,
And live and die a Pirate King.

For I am a Pirate King!
And it is, it is a glorious thing
To be a Pirate King!

For I am a Pirate King!
Chorus.
You are!
Hurrah for our Pirate King!
King.
And it is, it is a glorious thing
To be a Pirate King.
Chorus.
It is!
Hurrah for our Pirate King!
King & Chorus.
Hurrah for the/our Pirate King!

King. Darrell Fancourt as the Pirate King
1926

When I sally forth to seek my prey
I help myself in a royal way.
I sink a few more ships, it?s true,
Than a well-bred monarch ought to do;
But many a king on a first-class throne,
If he wants to call his crown his own,
Must manage somehow to get through
More dirty work than ever I do,

For I am a Pirate King!
And it is, it is a glorious thing
To be a Pirate King!

For I am a Pirate King!
Chorus.
You are!
Hurrah for the Pirate King!
King.
And it is, it is a glorious thing
To be a Pirate King.
Chorus.
It is!
Hurrah for our Pirate King!
King & Chorus.
Hurrah for the/our Pirate King!
#+end_verse
#+latex: \clearpage
* Old Maui
#+begin_verse
It's a damn tough life full of toil and strife
We whalermen undergo
And we won't give a damn when the gales are done
How hard the winds did blow
We're homeward bound from the Arctic Grounds
With a good ship taut and free
And we won't give a damn when we drink our rum
With the girls of Old Maui

Rolling down to Old Maui, me boys
Rolling down to Old Maui
We're homeward bound from the Arctic Grounds
Rolling down to Old Maui

Once more we sail with a Northerly gale
Through the ice, and wind, and rain
Them coconut fronds, them tropical shores
We soon shall see again
For six hellish months we passed away
On the cold Kamchatka sea
But now we're bound from the Arctic Grounds
Rolling down to Old Maui

Rolling down to Old Maui, me boys
Rolling down to Old Maui
We're homeward bound from the Arctic Grounds
Rolling down to Old Maui

Once more we sail with the Northerly gale
Towards our Island home
Our whaling done, our mainmast sprung
And we ain't got far to roam
Our stans'l booms is carried away
What care we for that sound
A living gale is after us
Thank God we're homeward bound

Rolling down to Old Maui, me boys
Rolling down to Old Maui
We're homeward bound from the Arctic Grounds
Rolling down to Old Maui

How soft the breeze through the island trees
Now the ice is far astern
Them native maids, them tropical glades
Is awaiting our return
Even now their big, brown eyes look out
Hoping some fine day to see
Our baggy sails running 'fore the gales
Rolling down to Old Maui

Rolling down to Old Maui, me boys
Rolling down to Old Maui
We're homeward bound from the Arctic Grounds
Rolling down to Old Maui
Rolling down to Old Maui, me boys
Rolling down to Old Maui
We're homeward bound from the Arctic Grounds
Rolling down to Old Maui
#+end_verse
#+latex: \clearpage
* Pirates of the Black Flag
#+begin_verse
We welcome the night as black as our heart
Can't see, don't want, never had a naval chart
The thief's rule of law
Is an appropriation bill
We're the pirates of the Black Tide
Sailors if you will

It's no birthday cake if you want our employ
And to be like us is a mistake you will enjoy
When pirates rule the seas
The world's a better place
We're the pirates of the Black Tide
We're a wonderful disgrace
We're the mythical, pinnacle statement of
Your worst-est dream or vocabulary word
We're tyrannical, mechanical and people say
That we smell like death, you can't take that away

Yes, we're your worst fear and we know where you hide
We've hidden there before, we don't care how hard you've cried
We're the bottom of the barrel
When it comes to raising kids
We're pirates from the North Pole
We know just what you did

We have nightmares too, but we just call them dreams
We've taken this yachting thing out to the extreme
We're Type-A personalities, our therapy's a sword
We're the pirates of the Black Tide
We will not be ignored

We're the black-hearted, swashbuckled, never take a shower
Kind of guys obsessed a bit with fame and power
We're deplorable, horrible, scull and cross-bone ridden
Living on the ship where nothing is forbidden

Yes, we're your worst fear and we know where you sleep
So tucky, tuck in I wouldn't sleep too deep
We're the worst father figure
Figure out how not to scream
We're the pirates of the Black Tide
Hope you have sweet dreams
We're the Pirates of the Black Tide
Hope you have sweet dreams
#+end_verse
#+latex: \clearpage
* Pirates who don't do anything
#+begin_verse
[Intro: Narrator]
And now it's time for silly songs with Larry
The part of the show where Larry comes out and sings a silly song

Joining Larry are Pa Grape and Mister Lunt, who together, make up the infamous gang of scallywags "The Pirates Who Don't Do Anything"

[Chorus: Pirates]
We are the pirates who don't do anything
We just stay at home and lie around
And if you ask us to do anything
We'll just tell you we don't do anything
[Verse 1: Pa Grape]
Well, I've never been to Greenland
And I've never been to Denver
And I've never buried treasure in St. Louie or St. Paul
And I've never been to Moscow
And I've never been to Tampa
And I've never been to Boston in the fall

[Chorus: Pirates]
Cause we're the pirates who don't do anything
We just stay at home and lie around
And if you ask us to do anything
We'll just tell you we don't do anything

[Verse 2: Mr. Lunt]
And I never hoist the mainstay
And I never swab the poop deck
And I never veer to starboard
'Cause I never sail at all
And I've never walked the gangplank
And I've never owned a parrot
And I've never been to Boston in the fall

[Chorus: Pirates]
'Cause we're the pirates who don't do anything
We just stay at home and lie around
And if you ask us to do anything
We'll just tell you we don't do anything
[Verse 3: Larry]
Well, I've never plucked a rooster
And I'm not too good at ping pong
And I've never thrown my mashed potatoes
Up against the wall
And I've never kissed a chipmunk
And I've never gotten head lice
And I've never been to Boston in the fall

[Spoken Interlude: Pa Grape (Mr. Lunt)]
Huh? What are you talking about? What does a rooster or mashed potatoes have to do with being a pirate?
(Hey, that's right! We're supposed to sing about pirate-y things)
And who's ever kissed a chipmunk? That's just nonsense, why even bring it up? Am I right? What do you think?
(I think you look like Cap'n Crunch)
Huh? No I don't
(Do too)
Do not
(You're making me hungry)
That's it, you're walking the plank
(Says who?)
Says the Captain
(Oh yeah? Aye, aye, Cap'n Crunch! Hee hee hee)
Arrrgh
(Yikes)

[Verse 4: Larry]
And I've never licked a spark plug
And I've never sniffed a stinkbug
And I've never painted daisies
On a big red rubber ball
And I've never bathed in yogurt
And I don't look good in leggings
(You just don't get it)
[All:] And we've never been to Boston in the fall
[Outro]
Pa: Pass the chips! Who’s got the remote?
Larry: Here it is!
Lunt: Time for Geraldo!
Pa: It’s definitely time for Wapner
Lunt: Oh, I don’t like this show
Larry: Hey, look! I found a quarter!
#+end_verse
#+latex: \clearpage
* Professional Pirate
:PROPERTIES:
:Artist:   Muppet Treasure Island
:END:
#+begin_verse
[LONG JOHN]
When I was just a lad looking for my true vocation
My father said "Now son, this choice deserves deliberation
Though you could be a doctor or perhaps a financier
My boy, why not consider a more challenging career?"

[PIRATES]
Hey ho ho!
You'll cruise to foreign shores
And you'll keep your mind and body sound
By working out of doors
[LONG JOHN]
True friendship and adventure are what we can't live without

[PIRATES]
And when you're a professional pirate

[POLLY]
That's what the job's about

[LONG JOHN]
(spoken)
Upstage, lads. This is my only number

(sung)
Now take Sir Francis Drake, the Spanish all despise him
But to the British, he's a hero and they idolize him
It's how you look at buccaneers that makes them bad or good
And I see us as members of a noble brotherhood

[PIRATES]
Hey ho ho!
We're honorable men
And before we lose our tempers we will
Always count to ten

[LONG JOHN]
On occasion, there may be someone you have to execute
[PIRATES]
And when you're a professional pirate

[CLUELESS]
You don't have to wear a suit

...What?

[MONTY]
I could have been a surgeon, I like taking things apart

[POLLY]
I could have been a lawyer, but I just had too much heart

[CLUELESS]
I could have been in politics 'cause I've always been a big spender

[BLACK-EYED PEA]
(spoken)
And me, I could've been a contender

[LONG JOHN]
Some say that pirates steal and should be feared and hated
I say we're victims of bad press that's all exaggerated
We never stab you in the back, we never lie or cheat
We're just, in fact, the nicest guy you ever want to meet
(spoken)
Tell the truth, lad. Do you really think the Captain and the Squire are planning to share the treasure with the likes of us? Can't hear ya. No? And we being the rightful owners, Flint's own crew, who shed our blood getting it here. Join us lad. Donate your compass to the treasure hunt and get a full share!

[LONG JONG and PIRATES]
Hey ho ho!
It's one for all for one
And we'll share and share alike with you
And love you like a son
We're gentlemen of fortune and that's what we're bound to be
And when you're a professional pirate-

[LONG JOHN]
You'll be honest, brave, and free!
The soul of decency!
You'll be loyal and fair and on the square
But most importantly

[LONG JOHN and PIRATES]
When you're a professional pirate
You are always in the best of company!
#+end_verse
#+latex: \clearpage
* Randy Dandy Oh
#+begin_verse
Now we are ready to head for the Horn
Weigh, hey, roll an' go!
Our boots an' our clothes boys are all in the pawn
To be rollickin' randy dandy O!

Heave a pawl, oh, heave away
Weigh, hey, roll and go!
The anchor's on board an' the cable's all stored
To be rollickin' randy dandy O!

Oh, man the stout caps'n and heave with a will
Weigh, hey, roll an' go!
Soon we'll be drivin' her 'way up the hill
To be rollickin' randy dandy O!
Heave a pawl, oh, heave away
Weigh, hey, roll and go!
The anchor's on board an' the cable's all stored
To be rollickin' randy dandy O!

Heave away, bullies, ye parish-rigged bums
Weigh, hey, roll and go!
Take yer hands from yer pockets and don't suck yer thumbs
To be rollickin' randy dandy O!

Heave a pawl, oh, heave away
Weigh, hey, roll and go!
The anchor's on board an' the cable's all stored
To be rollickin' randy dandy O!

We're outward bound for Vallipo Bay
Weigh, hey, roll and go!
Get crackin', me lads, it's a hell of a way!
To be rollickin' randy dandy O!

Heave a pawl, oh, heave away
Weigh, hey, roll and go!
The anchor's on board an' the cable's all stored
To be rollickin' randy dandy O!

Heave a pawl, oh, heave away
Weigh, hey, roll and go!
The anchor's on board an' the cable's all stored
To be rollickin' randy dandy O!
#+end_verse
#+latex: \clearpage
* Roll the Wood Pile Down
:PROPERTIES:
:Artist:   The Dreadnoughts
:END:
#+begin_verse
Away down South where the cocks do crow
Way down in Florida
Them girls all dance to the old banjo
And we'll roll the woodpile down

Rollin! Rollin! Rollin the whole world round
That brown gal of mine's on the Georgia line!
And we'll roll the woodpile down!

Oh, what can you do in Tampa bay?
Way down in Florida
But give them yellow girls all your pay
And we'll roll the woodpile down

Rollin! Rollin! Rollin the whole world round
That brown gal of mine's on the Georgia line!
And we'll roll the woodpile down!

Them Cardiff girls ain't got no frills
Way down in Florida
They're skinny and tight as catfish gills
And we'll roll the woodpile down

Rollin! Rollin! Rollin the whole world round
That brown gal of mine's on the Georgia line!
And we'll roll the woodpile down!

Oh, why do them little girls love me so?
Way down in Florida
Because I don't tell all I know
And we'll roll the woodpile down

Rollin! Rollin! Rollin the whole world round
That brown gal of mine's on the Georgia line!
And we'll roll the woodpile down!

Oh, one more pull and that will do
Way down in Florida
For we're the boys to kick her through
And we'll roll the woodpile down

Rollin! Rollin! Rollin the whole world round
That brown gal of mine's on the Georgia line!
And we'll roll the woodpile down!
That brown gal of mine's on the Georgia line
And we'll roll the woodpile down!
#+end_verse
#+latex: \clearpage
* Row me Bully boys
#+begin_verse
And it's row me bully boys
We're in a hurry boys
We got a long way to go
And we'll sing and we'll dance
And bid farewell to France
And it's row me bully boys row

I'll sing you a song, it's a song of the sea
Row me bully boys row
I'll sing you a song if you'll sing it with me
And it's row me bully boys row

And it's row me bully boys
We're in a hurry boys
We got a long way to go
And we'll sing and we'll dance
And bid farewell to France
And it's row me bully boys row

While the first mate is plating the captain aboard
Row me bully boys row
He looks like a peacock with pistols and sword
And it's row me bully boys row

And it's row me bully boys
We're in a hurry boys
We got a long way to go
And we'll sing and we'll dance
And bid farewell to France
And it's row me bully boys row

The captain likes whiskey, the mate, he likes rum
Row me bully boys row
Us sailers like both but we can't get us none
And it's row me bully boys row

And it's row me bully boys
We're in a hurry boys
We got a long way to go
And we'll sing and we'll dance
And bid farewell to France
And it's row me bully boys row

Well farewell my love it is time for to roam
Row me bully boys row
The old blue peters are calling us home
And it's row me bully boys row

And it's row me bully boys
We're in a hurry boys
We got a long way to go
And we'll sing and we'll dance
And bid farewell to France
And it's row me bully boys row

And it's row me bully boys
We're in a hurry boys
We got a long way to go
And we'll sing and we'll dance
And bid farewell to France
And it's row me bully boys row
#+end_verse
#+latex: \clearpage
* Sailing For Adventure
:PROPERTIES:
:Artist:   Muppet Treasure Island
:END:
#+begin_verse
[PIRATES]
When the course is laid and the anchor's weighed
A sailor's blood begins racing
With our hearts unbound and our flag unfurled

[PIRATE]
We're on our way and off to see the world

[COMPANY]
On our way and off to see the world
Hey, ho, we'll go
Anywhere the wind is blowing

[PIRATE]
Manly men are we

[COMPANY]
Sailing for adventure on the deep blue sea

[SAM/MR. ARROW]
(spoken)
Safely now, Mr. Silver! Let's not get sloppy just because we're singing!

[PIRATES]
Danger walks the deck, we say what the heck
We laugh at the perils we're facing

[GONZO]
Every storm we ride is its own reward

[RIZZO]
And people die by falling overboard
[COMPANY]
People die by falling overboard

Hey, ho, we'll go
Anywhere the wind is blowing
Hoist the sails and sing
[FOZZIE/SQUIRE TRELAWNEY]
Sailing for adventure on the big blue wet thing

[POLLY]
I love to see them cry when they walk the plank

[CLUELESS]
I prefer to cut a throat

[MAD MONTY]
I love to hang 'em high and watch their little feet try to walk in the air while their faces turn blue

[CLUELESS]
(spoken)
Just kidding. Haha

[ALL THREE]
It's a good life on a boat

[COMPANY]
There are distant lands with burning sands
That call across the ocean

[RATS]
There are bingo games every fun-filled day
[FEMALE RAT]
And margaritas at the midnight buffet

[COMPANY]
Margaritas at the midnight buffet

Hey, ho, we'll go
Anywhere the wind is blowing

[STATLER and WALDORF/FIGUREHEADS]
Should have took the train!

[COMPANY]
Sailing for adventure on the bounding main

[JIM]
The salty breezes whisper
Who knows what lies ahead?
I just know I was born to lead
The life my father led

[LONG JOHN]
The stars will be our compass
Wherever we may roam
And our mates will always be
Just like a family
And though we may put in to port
The sea is always home

[FOZZIE/SQUIRE TRELAWNEY]
(spoken)
All right, Mr. Bimbo. I didn't know you had such a good singing voice! ... You're welcome!

[COMPANY]
We'll chase our dreams standing on our own
Over the horizon to the great unknown

Hey, ho, we'll go
Anywhere the wind is blowing
Home and brave and free!

[COMPANY]
Sailing for adventure-

[RIZZO]
It's so nauseating!

[COMPANY]
Sailing for adventure-
[GONZO]
So exhilarating!

[COMPANY]
Sailing for adventure-

[RATS]
We're all celebrating!

[COMPANY]
On the deep blue sea!
#+end_verse
#+latex: \clearpage
* Sally Brown/Roll Boys, Roll
#+begin_verse
[Verse 1]
Oh! Sally Brown, she's the gal for me, boys
Roll, boys! Roll, boys, roll!
Sally Brown, she's the girl for me, boys
Weigh high, Miss Sally Brown!

[Verse 2]
It's down to Trinidad to see Sally Brown, boys
Roll, boys! Roll, boys, roll!
Down to Trinidad to see Sally Brown, boys
Weigh high, Miss Sally Brown!
[Verse 3]
She's lovely on the foreyard, and she's lovely down below, boys
Roll, boys! Roll, boys, roll!
She's lovely cause she loves me, that's all I want to know, boys
Weigh high, Miss Sally Brown!

[Verse 4]
Old Captain Baker, how do you store yer cargo?
Roll, boys! Roll, boys, roll!
Some I stow forward, and some I stow after
Weigh high, Miss Sally Brown!

[Verse 5]
Forty fathoms or more below, boys
Roll, boys! Roll, boys, roll!
There's forty fathoms or more below, boys
Weigh high, Miss Sally Brown!

[Verse 6]
Oh, weigh high ya, and up she rises
Roll, boys! Roll, boys, roll!
Weigh high ya, and the blocks is different sizes
Weigh high, Miss Sally Brown!

[Verse 7]
Oh, one more pull, don't ya hear the mate a-bawling?
Roll, boys! Roll, boys, roll!
One more pull, that's the end of all our hauling
Weigh high, Miss Sally Brown!
[Verse 8]
Sally Brown, she's the gal for me, boys
Roll, boys! Roll, boys, roll!
Sally Brown, she's the girl for me, boys
Weigh high, Miss Sally Brown!
#+end_verse
#+latex: \clearpage
* Santiana
:PROPERTIES:
:Artist:   The Longest Johns
:END:
#+begin_verse
[Verse 1]
Oh! Santiana gained a day
Away Santiana!
"Napoleon of the West", they say
Along the plains of Mexico

[Chorus]
Well, heave 'er up and away we'll go
Away Santiana!
Heave 'er up and away we'll go
Along the plains of Mexico
[Verse 2]
She's a fast clipper ship and a bully good crew
Away Santiana!
And an old salty yank for a captain too
Along the plains of Mexico

[Chorus]
Well, heave 'er up and away we'll go
Away Santiana!
Heave 'er up and away we'll go
Along the plains of Mexico

[Verse 3]
Santiana fought for gold
Away Santiana!
Around Cape Horn through the ice and snow
Along the plains of Mexico

[Chorus]
Well, heave 'er up and away we'll go
Away Santiana!
Heave 'er up and away we'll go
Along the plains of Mexico

[Verse 4]
T'was on the field of Molly-Del-Ray
Away Santiana!
Well both his legs got blown away
Along the plains of Mexico
[Chorus]
Well, heave 'er up and away we'll go
Away Santiana!
Heave 'er up and away we'll go
Along the plains of Mexico

[Verse 5]
It was a fierce and bitter strife
Away Santiana!
The general Taylor took his life
Along the plains of Mexico

[Chorus]
Well, heave 'er up and away we'll go
Away Santiana!
Heave 'er up and away we'll go
Along the plains of Mexico

[Verse 6]
Santiana, now we mourn
Away Santiana!
We left him buried off Cape Horn
Along the plains of Mexico
#+end_verse
#+latex: \clearpage
* Shiver Me Timbers
:PROPERTIES:
:Artist:   Muppet Treasure Island
:END:
#+begin_verse
Shiver my timbers, shiver my soul
Yo ho heave ho
There are men whose hearts are as black as coal
Yo ho heave ho

And they sailed their ship cross the ocean blue
A blood-thirsty captain and a cut-throat crew
It's as dark a tale as was ever told
Of the lust for treasure and the love of gold

Shiver my timbers, shiver my sides
Yo ho heave ho
There are hungers as strong as the wind and tides
Yo ho heave ho
And those buccaneers drowned their sins in rum
The devil himself would have to call them scum
Every man aboard would have killed his mate
For a bag of guineas or a piece of eight
(A piece of eight)
(A piece of eight)

Five, six, seven, eight!

Hoola wacka! Oola wacka! Something not right
Many wicked icky things gonna happen tonight
Hoola wacka! Oola wacka! Sailor man beware
When there's money in the ground there's murder in the air
(Murder in the air)

One more time now

Shiver my timbers, shiver my bones
Yo ho heave ho
There are secrets that sleep with old Davy Jones
Yo ho heave ho

When the mainsail's set and the anchor's weighed
There's no turning back from any course that's laid
And when greed and villainy sail the sea
You can bet your boots there'll be treachery
Shiver my timbers, shiver my sails
Dead men tell no tales
#+end_verse
#+latex: \clearpage
* Space Shanty
:PROPERTIES:
:Artist:   The Senate
:END:
#+begin_verse
[Verse 1]
Oh the whiskey is floating won't stay in ye glass
I'm weightless and spinning and drunk off me ass
Oh the whiskey is floating in a sphere o'er me head
If we don't clear this wormhole we're surely be dead

[Chorus]
So reach for the whiskey boys reach for the stars
They won't stop us drinking on Venus or Mars
So reach for the whiskey boys reach for the sky
For the vacuum of space sucks the bottles all dry
[Verse 2]
Oh infinite booty awaits us in space
We'll pillage and plunder with fervor and grace
That's what my astronomical unit is for
Let's party where no one has partied before

[Chorus]
So reach for the whiskey boys reach for the stars
They won't stop us drinking on Venus or Mars
So reach for the whiskey boys reach for the sky
For the vacuum of space sucks the bottles all dry

[Verse 3]
Alone in the cockpit I gaze at the stars
I drink and I think of my home
(He thinks of his home)
Of my home

[Verse 4]
Our thrusters are the hottest that you've ever felt
They might just unbuckle your asteroid belt
We're honing our moonwalking skills as we speak
We'll dance on Uranus by this time next week

[Chorus] x2
So reach for the whiskey boys reach for the stars
They won't stop us drinking on Venus or Mars
So reach for the whiskey boys reach for the sky
For the vacuum of space sucks the bottles all dry
#+end_verse
#+latex: \clearpage
* The Last Shanty
#+begin_verse
[Verse 1]
Well me father often told me when I was just a lad
A sailor's life is very hard, the food is always bad
But now I've joined the navy, I'm aboard a man-o-war
And now I've found a sailor ain't a sailor any more

[Chorus]
Don't haul on the rope, don't climb up the mast
If you see a sailing ship it might be your last
Just get your civvies ready for another run-ashore
A sailor ain't a sailor, ain't a sailor anymore
[Verse 2]
Well the killick of our mess he says we had it soft
It wasn't like that in his day when we were up aloft
We like our bunks and sleeping bags, but what's a hammock for?
Swinging from the deckhead, or lying on the floor?

[Chorus]
Don't haul on the rope, don't climb up thе mast
If you see a sailing ship it might be your last
Just get your civvies rеady for another run-ashore
A sailor ain't a sailor, ain't a sailor anymore

[Verse 3]
They gave us an engine that first went up and down
Then with more technology the engine went around
We know our steam and diesels but what's a mainyard for?
A stoker ain't a stoker with a shovel anymore

[Chorus]
Don't haul on the rope, don't climb up the mast
If you see a sailing ship it might be your last
Just get your civvies ready for another run-ashore
A sailor ain't a sailor, ain't a sailor anymore

[Verse 4]
Two cans of beer a day and that's your bleeding lot
And now we've got an extra one because they stopped The Tot
So we'll put on our civvy-clothes find a pub ashore
A sailor's just a sailor just like he was before
[Chorus]
Don't haul on the rope, don't climb up the mast
If you see a sailing ship it might be your last
Just get your civvies ready for another run-ashore
A sailor ain't a sailor, ain't a sailor anymore
Don't haul on the rope, don't climb up the mast
If you see a sailing ship it might be your last
Just get your civvies ready for another run-ashore
A sailor ain't a sailor, ain't a sailor anymore
#+end_verse
#+latex: \clearpage
* The Ship is Fine
:PROPERTIES:
:Artist:   Jolly Rogers
:END:
#+begin_verse


There's not a thing wrong with this ship
In fact, she is just fine
But there would be some changes
If if this vessel it were mine
Nothing unrealistic or too drastic or severe
Just some subtle tweaks to improve the atmosphere!

I would have a great big deck
Plated in solid gold!
'Cause being teased about my little deck
Is really gettin' old! (happens a lot)
I'd sail from south tortuga
All the way up to Quebec
And in each port I'd shout: Hey, sailor!
Wanna ride my great big deck?
(It's enormous! - it's okay, it's okay)

There's not a thing wrong with this ship
In fact, she is just fine
But there would be some changes
If if this vessel it were mine
Nothing unrealistic or too drastic or severe
Just some subtle tweaks to improve the atmosphere!

Let's see, uh
I'd get rid of all the water
From down in the ballast hole (but we'll tip over!)
And replace it with some good dark rum
Where it can stay nice and cold!
Every man aboard the ship can drink
Until he's had his fill
And the only rude we'd enforce
Is that noone's allowed to spill!
(How about that? Take that, you'd have to replace it later)

There's not a thing wrong with this ship
In fact, she is just fine
But there would be some changes
If if this vessel it were mine
Nothing unrealistic or too drastic or severe
Just some subtle tweaks to improve the atmosphere!

I'd strip her down just to a rudder
A mast and a wheel (minimalism!)
I'd make her long and hard - and hollow
And cover her in steel! (urr!)
She'd be a giant floating cannon
No need for cabins and walls! (we-we need them)
And everyone would shiver
When they saw the size of my balls!
(I'm shivering already, you've seen them? They're huge!)

There's not a thing wrong with this ship
In fact, she is just fine
But there would be some changes
If if this vessel it were mine
Nothing unrealistic or too drastic or severe
Just some subtle tweaks to improve the atmosphere!

I'd replace the bunks and hammocks
With big four-poster beds (ooh, okay!)
And I'd get rid of most the crew like you, lot
And hire trollops on instead
She'd be a floating brothel
And I'd be her captain bow
I'd have more fun than any pirate
And I'd make a lot more gold (arrogant jerk)

There's not a thing wrong with this ship
In fact, she is just fine
But there would be some changes
If if this vessel it were mine
Nothing unrealistic or too drastic or severe
Just some subtle tweaks to improve the atmosphere!

I'd get rid of all the sails
And find something better than the wind (what?)
Perhaps some sort of intermittent combustion engine
With reciprocating pistons
And a fuel source based on heat!
We could - hey! - woah, woah, woah!
Well, forget it you mooks
Let's go with devin's brothel plan
Wouldn't that be sweet? (Yeaah!)

There's not a thing wrong with this ship
In fact, she is just fine
But there would be some changes
If if this vessel it were mine
Nothing unrealistic or too drastic or severe
Just some subtle tweaks to improve the atmosphere!
Nothing unrealistic or too drastic or severe
Just some subtle tweaks to improve the atmosphere!
#+end_verse
#+latex: \clearpage
* Twiddles
:PROPERTIES:
:Artist:   Misbehavin' Maidens
:END:
#+begin_verse
Oh you hear a lot of stories 'bout the sailors and their sport
About how every sailor has a girl in every port
But if you added 2 and 2 you’d figure out right quick
It's just because the girls all have a lad on every ship

[Chorus]
And it's Twiddle ee ai dee ai dee ai
Twiddle ee ai dee ei
It’s often times a man will leave you broken with dismay
And it's Twiddle ee ai dee ai dee ai
Twiddle ee ai dee ei
There's other things to twiddle when the men have sailed away
Lucky Annie was a lady who'd been pleased by many men
They all would sail away but then they'd come right back again
But if they never sailed her way she really didn't care
Cause I know that you don't need a man to twiddle under there

[Chorus]
And it's Twiddle ee ai dee ai dee ai
Twiddle ee ai dee ei
It’s often times a man will leave you broken with dismay
And it’s Twiddle ee ai dee ai dee ai
Twiddle ee ai dee ei
There's other things to twiddle when the men have sailed away

Saber had her lovers, they came in at every door
You could even say that she was really quite a whore
But when she needs some pleasing, she knows just where to go
I grab my good friend Madam Rouge and we go down below

[Chorus]
And it’s Twiddle ee ai dee ai dee ai
Twiddle ee ai dee ei
It's often times a man will leave you broken with dismay
And it's Twiddle ee ai dee ai dee ai
Twiddle ee ai dee ei
There's other things to twiddle when the men have sailed away
There was a time when Rouge she found the sailor men a bore
Each new one was more tiresome than the one she had before
Now she finds more joy in breeches than she ever did of old
I’m more fond of their bulges when they're pouches full of gold

[Chorus]
And it's Twiddle ee ai dee ai dee ai
Twiddle ee ai dee ei
It's often times a man will leave you broken with dismay
And it's Twiddle ee ai dee ai dee ai
Twiddle ee ai dee ei
There's other things to twiddle when the men have sailed away

Why the boys would look at her, it puzzled poor Flint Locke
She would sit and smile and nod and let them brag and talk
But if they tried to touch her well she'd put them on the run
Cause why would I need a lover when I've got myself a gun

[Chorus]
And it's Twiddle ee ai dee ai dee ai
Twiddle ee ai dee ei
It's often times a man will leave you broken with dismay
And it's Twiddle ee ai dee ai dee ai
Twiddle ee ai dee ei
There's other things to twiddle when the men have sailed away
So next time you're with a lady and she takes you to her bed
Be sure to please her well, and remember what we've said
For if you do not treat her right then know that this is true
Us ladies all can have our fun without involving you

[Chorus x2]
And it's Twiddle ee ai dee ai dee ai
Twiddle ee ai dee ei
It's often times a man will leave you broken with dismay
And it's Twiddle ee ai dee ai dee ai
Twiddle ee ai dee ei
There's other things to twiddle when the men have sailed away
And it's Twiddle ee ai dee ai dee ai
Twiddle ee ai dee ei
It's often times a man will leave you broken with dismay
And it's Twiddle ee ai dee ai dee ai
Twiddle ee ai dee ei
There's other things to twiddle when the men have sailed away
#+end_verse
#+latex: \clearpage
* Tyme Flies When You're Having Rum
:PROPERTIES:
:Artist:   Pirates for Sail
:END:
#+begin_verse
No future was there in London for a poor man's son like me
So I left my home and I went to seek my fortune on the sea
I signed aboard a merchant ship bound for the west indies
And six weeks out we tapped into the winds of piracy

There we sails on the horizon and we tried to make a run
And when we saw that black flag then our running it was done
And when those pirates boarded us they told us one by one
"You can die or join our crew me boys
Time flies whеn you're having rum!"
Time flies whеn you're having rum me boys
Time flies when you're having rum
When you're sailing under the black flag
And you're firing all your guns
When you take a spanish treasure ship
You divide by the rule of thumb
Our voyage will be over soon enough
Time flies when you're having rum

With a pistol to my forehead
Then my choice was all too clear
I took leave of that merchant ship and became a buccaneer
And though they spared my life I think that if the truth be told
I joined them for the promise of
Adventure, rum and gold

The quartermaster handed me a cutlass and a gun
And as I signed their articles the captain told me "Son
Us gentlemen of fortune live life fast and on the run
So step right up and take your share
Time flies when you're having rum!"

Time flies when you're having rum me boys
Time flies when you're having rum
When you're sailing under the black flag
And you're firing all your guns
When you take a spanish treasure ship
You divide by the rule of thumb
Our voyage will be over soon enough
Time flies when you're having rum
For two long years I sailed with them
Around the Spanish Main
And capture ships from Portugal
From England, France and Spain
We took what we could and we gave none back
For that's the pirate's code
And in our wake the Caribbean Sea ran red with blood

The admiralty in London sent a fleet to hunt us down
A traitor in Port Royal told them where we could be found
They surrounded us in Nassau, the captain shouted
"Let 'em come! The fight will be over soon enough
Time flies when you're having rum."


Time flies when you're having rum me boys
Time flies when you're having rum
When you're sailing under the black flag
And you're firing all your guns
When you take a spanish treasure ship
You divide by the rule of thumb
The voyage will be over soon enough
Time flies when you're having rum

We ran the red flag up and then we readied all our guns
No quarter would we give and in turn expected none
We got off one good broadside
But outnumbered ten to one
They took out half our crew
And then our pirating was done
They took us back to London Town nder key and lock
The hangman's noose was swinging at the execution dock
The captain turned and said to me, "We had fine sailing son
The voyage it was over all too soon
Time flies when you're having rum."

Time flies when you're having rum me boys
Time flies when you're having rum
When you're sailing under the black flag
And you're firing all your guns
When you take a spanish treasure ship
You divide by the rule of thumb
Our voyage will be over soon enough
Time flies when you're having rum

Now as you've listened to this tale by know
I'm sure you have surmised
That I slipped the hangman's cable
And escaped him with my life
But how I got away
That's another story son
My voyages they aren’t over yet
Time flies when you're having rum!


Time flies when you're having rum me boys
Time flies when you're having rum
When you're sailing under the black flag
And you're firing all your guns
When you take a spanish treasure ship
You divide by the rule of thumb
Our voyage will be over soon enough
Time flies when you're having rum
#+end_verse
#+latex: \clearpage
* Voodoo Man
:PROPERTIES:
:Artist:   Jolly Rogers
:END:
#+begin_verse
He was a nice young sailor lad, as green as green could be
When he first joined our crew for a life of piracy
When a storm nearly capsized us, he was thrown from the ship
Stranded on Hispaniola, right there on the western tip
When the crew next saw him they could not believe their eyes
There was little left of the young man that one could recognize
His hair was long a braided, and he looked ready for war
But he smiled and said " Hello mates. I'm your new bokor

Now he wears more tattoos than clothes
With a ring on every finger and bone in his nose
When he starts his chanting we don't always understand
But we always listen to him, cause he's our voodoo man
The captain said "Now listen boys, I think we should turn back
There's a storm a brewing and that beast is building fast."
The bokur said "Just wait a minute and Captain keep your course"
And he went back to his cabin but the storm it just got worse

We heard howls, and moans, and a bang, and a crash
We saw thick black smoke and a fiery flash
We could smell the lighting and we just stared at his door
And when we started to relax, it started up once more

He rushed out and said "We'll need every inch of sail."
And a swath of clear blue sky split the monstrous gale
The wind filed every sail and tightened every line
As we passed we saw the storm crashed back in behind

Now he wears more tattoos than clothes
With a ring on every finger and bone in his nose
When he starts his chanting we don't always understand
But we always listen to him, cause he's our voodoo man

While hunting down a merchant ship around the rocky shore
We came around the island to a massive Man o' War
The captain said " Now listen boys. We're about to meet our doom."
And the bokor shouted "Never fear"
And he ran down to his room
We heard howls, and moans, and a bang, and a crash
We saw thick black smoke and a fiery flash
We could smell the lighting and we just stared at his door
And when we started to relax, it started up once more

"Fire two shots!" he shouted and they went off right on cue
Both shots found their target and their powder hold it blew
The Man o' War bust into flames and it began to pitch
And we stole enough from her to make sure we were rich

He still wears more tattoos than clothes
With a ring on every finger and bone in his nose
When he starts his chanting we don't try to understand
But we always listen to him, cause he's our voodoo man
We always listen to him, cause he's our voodoo man
We always listen to him, cause he's our voodoo man
#+end_verse
#+latex: \clearpage
* Wellerman
#+begin_verse
[Verse 1]
There once was a ship that put to sea
The name of the ship was the Billy of Tea
The winds blew up, her bow dipped down
O blow, my bully boys, blow (Huh!)

[Chorus]
Soon may the Wellerman come
To bring us sugar and tea and rum
One day, when the tonguin' is done
We'll take our leave and go
[Verse 2]
She had not been two weeks from shore
When down on her, a right whale bore
The captain called all hands and swore
He'd take that whale in tow (Huh!)

[Chorus]
Soon may the Wellerman come
To bring us sugar and tеa and rum
One day, when the tonguin' is donе
We'll take our leave and go

[Verse 3]
Before the boat had hit the water
The whale's tail came up and caught her
All hands to the side, harpooned and fought her
When she dived down low (Huh!)

[Chorus]
Soon may the Wellerman come
To bring us sugar and tea and rum
One day, when the tonguin' is done
We'll take our leave and go

[Verse 4]
No line was cut, no whale was freed
The Captain's mind was not of greed
But he belonged to the Wellerman's creed
She took that ship in tow (Huh!)
[Chorus]
Soon may the Wellerman come
To bring us sugar and tea and rum
One day, when the tonguin' is done
We'll take our leave and go

[Verse 5]
For forty days, or even more
The line went slack, then tight once more
All boats were lost, there were only four
But still that whale did go (Huh!)

[Chorus]
Soon may the Wellerman come
To bring us sugar and tea and rum
One day, when the tonguin' is done
We'll take our leave and go

[Verse 6]
As far as I've heard, the fight's still on
The line's not cut and the whale's not gone
The Wellerman makes his regular call
To encourage the Captain, crew, and all (Huh!)

[Chorus]
Soon may the Wellerman come
To bring us sugar and tea and rum
One day, when the tonguin' is done
We'll take our leave and go (Huh!)
Soon may the Wellerman come
To bring us sugar and tea and rum
One day, when the tonguin' is done
We'll take our leave and go
#+end_verse

#+latex: \clearpage
